language: c++
sudo: required
dist: trusty
os: 
  - linux
  - osx
compiler:
  - clang
  - gcc
before_install: ./misc/travis-ci-before.sh
script: ./misc/travis-ci-build.sh
branches:
  only:
    - /^blowfish-.*$/
matrix:
  exclude:
    - os: osx
      env: PLATFORM=mingw32 ARCH=x86
    - os: osx
      env: PLATFORM=mingw32 ARCH=x86_64
    - os: osx
      compiler: gcc
env:
  global:
    - secure: KVJv0WLpTVIPnO7dB45HOLXyQ2ToC68axKoh0Gt8+pjyX6UcDkf3Bh7ug1ZjAGSbn5CaiNnHaAQBb0n4xoOZmusnrZdr59H/GaxcCbyUW4dhPy9YNoKh+bWLUwlXb5R2z73Eh3mj7r+7YsI/XH5qmiw2BZOUv/Dwkt6ad1IuesVLf1u+DwoPVdnKUiHSF+17QN4knsTucahjkUY7HDlAmhLyxfN65x1zIvoD/uKKNg1k+Q/knC9gJ/VhBsuGznD3ZK7MIf+hRJEHISbOcGx9OIOIks1SXRYT8U4fXM/3Ahrw28ljtH6WC3+vgQZjxuRn1qkE50BjLCp3O8xiCalRT//15g0WQDTgQma2tuLKeqnxKn1rQe2wVF+ENizRiNYeIbYnOqxRJW2zXSqFRMSEEVf/ZX4z+AjEp1sY1vKuB9X30l9ZwQKCMpKJthXRu6zVt1B6+D0C8FTfN1lnhDohAWG4MdRFmHK00tWIyzmRjp5rcp82Ip1IckZis0fwK/yfAnXZDdGGSOOvr1C3aDzdD56/z1WgN4hxrrTewPuq/Sr4S2kOiJSyVL6qX1+PtjGMVEimhlCQA0ntxsXUKCd5hTy7RFeC2m1yWT3kQdm7V766BPTzshlVg7syjKNqXFNbVEOHvqbQi0q/GNqe5qzplCABA7ivhBA/Be07fId0VXs=
  matrix:
    - ARCH=x86 USE_CODEC_VORBIS=1 USE_FREETYPE=1
    - ARCH=x86_64 USE_CODEC_VORBIS=1 USE_FREETYPE=1
    - PLATFORM=mingw32 ARCH=x86
    - PLATFORM=mingw32 ARCH=x86_64
notifications:
  email: false
addons:
  coverity_scan:
    project:
      name: wtfbbqhax/tremulous
      description: Build submitted via Travis CI
    notification_email: blowfish+coverity@badsec.org
    build_command_prepend: make clean
    build_command: make release
    branch_pattern: coverity_scan 
deploy:
  provider: releases
  api_key:
    secure: tm8Ie0GVvv7Sdb4vxtewTWGJztrPMSrws9KoXNUHRenbnqujrFusFabef+2YDZbWq2+Ki85ey2SXvYiBWJs3FKVnePc/s2ax0JSVJCUvGntQC1PiD/+xcpWYzy9DACQtqXRdwRx2aURqpj6KXHJACtbo4dUa028xObcwAB1FmIi/SGafUzU0JdyJsggNhFmO+c4hk9Vo6uMXFBrXXhZbMAQT2dFvTqtwX+cWzbMHgCRIXLuevuOpq/oONL6RHQIgErzfLwrnyzbrNt/fftFttZm7blzIKzi4txpI0g5lHEAAgauoYRJngPDfDQtiN0bgTMQNuGhqgf52PKUAr4eZ4QZNn+t/tyLauqRPfPm+m9a7QOYLye34qDhjPt87vYnUUfpdwftCwd5UJs65b3CFNp+grARxU1bRld4DkcyOVKPH4pMQN1nP3FNpmyKNZdFOrq6iq7hrQ7xCfqnL5xuPVIqWJa3cE5qanQsIwHERgyDjEGkwCRjZofAqioCDzSCKBqnTkXVoBczLTm/I4xrsYCnbwfb5cKR3p910wR1IR4JxX2XjIn78vFAlKYr2BOModjLO3oQym76NBOmaf0LO8BP8kJi6q2CxuFGnbK7qlhn8CHJb9vLFh7ZJNeRiGkPSP2lf32xm/MnpFgNuNXGF3mRwxL9M/eKXRaL9feDouYM=
  file: 
    - build/release-darwin-x86_64.zip
    - build/release-darwin-x86.zip
    - build/release-linux-x86.zip
    - build/release-linux-x86_64.zip
    - build/release-mingw32-x86.zip
    - build/release-mingw32-x86_64.zip
  on:
    repo: wtfbbqhax/tremulous
    branch: blowfish-alpha-1
