language: cpp
sudo: required
dist: trusty
services:
- docker
git:
  depth: 5
script:
- ./misc/travis-ci-build.sh
notifications:
  email:
    on_success: change
    on_failure: change
matrix:
  include:
  - os: linux
    compiler: gcc
    before_install:
    - docker build -t wtfbbqhax/tremulous:v1 .
    - docker run -v $(pwd)/build:/usr/src/build wtfbbqhax/tremulous:v1 ./misc/docker-build.sh
  - os: osx
    osx_image: xcode8
    compiler: clang
    env: USE_RESTCLIENT=1 USE_CODEC_VORBIS=1 USE_FREETYPE=1 ARCH=x86_64
    before_install:
    - brew update
    - brew install freetype --universal
    - rm -rf build

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: euPVnsrXbfQN095snEmxb+52vWsEg5bcmJY6fP9k7/J4uz8r/QMYxIknPueFGnPLd2iP2IHwu933iT2k5oc/acCuib7kiy6kUdeC29epik+Nql3BnSEi820GjlQoYBcsWm5a26pGOSRR/yqCJXrY5w2CBFOqV7t4n6iFcl2Ks/rPrNmkfGdq1WBq6JHXGwBUU+UwUDwiaBwmMUBYdKMHmxvjWcGiyeQNxwaC3+IwEOzNx/B8u4o8qwksdwHRkMyUAnxcxY1TwpjV1b/4YmxL6F10zOyJQxJ8alXvgNzzEmJfxKSG27Zma48++4kfSq4ReB2ZwuCj7rqEKnQ/htE0jbwEcjKEt3Ii4bVReSNVGD5BWPL7Qkm1dx5lvL1zRaqyOnJQs3CJAOnX0L5LHrP12Dw1cCXHSSDdBMy+dRA1owVKvO3osoAVJUqZCxl6PYxVfSxNu9FlP4fxypSpgPl5458NwK8r1wjZfTprFNV4dlXsQrdc8B/EttwX9n9O9JLzrrjV7K9IvyA7ArYz5IDiSagOb4wOktDfepfHJioaFZIWgYQ4hGXXQJm/qDa4J/KSYME74knHbHkqx3eAo3T9/ofMDLyrK5CCIAmoGI0pcPgbuvLvNCVrVzGyaH7j8WxIBG0AN16I1MAs5+cJ4gCFgEsCvf30O++zqYIaOujpZ70=
  file_glob: true
  file: "build/*.zip"
  on:
    repo: GrangerHub/tremulous
    tags: true
